### ISSUE TITLE
DashBoard post non update

### ISSUE THREAD

**Issue by ghost** [CWCLAN/humhub-theme-cwclan#1]
I am glad to publish your first issue. I really like your theme and I use it since a week.

I discovered that the form you included on dashboard to publish a post in the personal wall is not totally working because at difference of this form in any space, after publish, the page is not showing it the content. It´s needed to refresh the site so by consequence, I have users publishing few times same post until they discover it and they delete all duplication.

If you find a way to fix it, may you send me the modifications you made because I customised a lot the style and I don t want to loose all my mods.

Thank you very much.

**Comment by globeFrEak** [comment]
This is not a bug from the theme!
The personal wall is a private wall (default humhub configuration).
You as admin can set the user walls as public by default!
![2017-05-04 16_54_58-administration - cwclan de](https://cloud.githubusercontent.com/assets/589071/25710031/4ec07666-30eb-11e7-8a9d-96bbbd721354.png)


Other users can only see the content of an user wall when a friendship with this user exist, or the user self can set his wall to public.
